spring:
  application:
    name: charter-app
  profiles:
    active: local
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: "GMT+8"
    serialization:
      write-dates-as-timestamps: false # 时间格式化不转换为时间戳